# Generated by Django 4.0.5 on 2022-06-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_converter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodelconversion',
            name='file_description',
            field=models.TextField(default='Hey, I am the default description :)'),
        ),
    ]
