# Generated by Django 4.0.5 on 2022-06-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_converter_app', '0002_filemodelconversion_file_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodelconversion',
            name='converted_file',
            field=models.FileField(default='settings.MEDIA_ROOT/new_one.csv', max_length=150, upload_to='json_or_csv/'),
        ),
    ]
