# Generated by Django 4.0.5 on 2022-06-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_converter_app', '0003_filemodelconversion_converted_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodelconversion',
            name='converted_file',
            field=models.FileField(default='csv_or_json/new_one.csv', max_length=150, upload_to='json_or_csv/'),
        ),
    ]
