# Generated by Django 4.0.5 on 2022-06-20 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_converter_app', '0004_alter_filemodelconversion_converted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodelconversion',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filemodelconversion',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
    ]
