# Generated by Django 4.0.5 on 2022-06-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_converter_app', '0005_filemodelconversion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodelconversion',
            name='file_description',
            field=models.TextField(null=True),
        ),
    ]
